# Generated by Django 2.1.5 on 2021-04-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='home/')),
            ],
            options={
                'verbose_name': 'Display',
                'verbose_name_plural': 'Displays',
            },
        ),
    ]
