# Generated by Django 2.1.5 on 2021-04-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='furnitures/')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'New',
            },
        ),
        migrations.AlterField(
            model_name='furnitures',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
