# Generated by Django 2.1.5 on 2021-04-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0002_auto_20210422_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
